#!/usr/bin/env node
/**
 * telegram-to-discord — installation wizard
 *
 * Interactive setup for the Cloudflare Worker that mirrors public Telegram
 * channels into a Discord channel via webhook. Safe to re-run at any time:
 * every step is idempotent (login / KV / deploy are reused if already done).
 *
 * Usage:  npm install && node wizard.js
 */
import { spawnSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync } from 'node:fs';

const c = process.stdout.isTTY ? {
  b: s => `\x1b[1m${s}\x1b[0m`,
  dim: s => `\x1b[2m${s}\x1b[0m`,
  green: s => `\x1b[32m${s}\x1b[0m`,
  red: s => `\x1b[31m${s}\x1b[0m`,
  cyan: s => `\x1b[36m${s}\x1b[0m`
} : { b: s => s, dim: s => s, green: s => s, red: s => s, cyan: s => s };

const line = () => console.log(c.dim('─'.repeat(62)));

// read without extra deps
import { createInterface } from 'node:readline';
const rl = createInterface({ input: process.stdin, terminal: !!(process.stdout.isTTY) });
function askQ(question, def = '') {
  return new Promise(resolve => {
    rl.question(c.b(question) + (def ? c.dim(` [${def}]`) : '') + ' ', answer => {
      resolve(answer.trim() || def);
    });
  });
}

function run(cmd, args, opts = {}) {
  const r = spawnSync(cmd, args, { encoding: 'utf8', shell: true, ...opts });
  return { ok: r.status === 0, out: (r.stdout || '') + (r.stderr || ''), status: r.status };
}

const die = msg => { console.error('\n' + c.red('✖ ' + msg)); rl.close(); process.exit(1); };

async function main() {
  line();
  console.log(c.cyan.b('  Telegram → Discord relay  ·  Cloudflare Workers setup wizard'));
  line();
  console.log(`
This wizard will:
  ${c.dim('1.')} install dependencies
  ${c.dim('2.')} pick the Telegram channels to mirror
  ${c.dim('3.')} validate your Discord webhook (and post a test message)
  ${c.dim('4.')} log in to Cloudflare (browser popup, once)
  ${c.dim('5.')} create the KV namespace and deploy the Worker
  ${c.dim('6.')} store the webhook as an encrypted secret and run a live sync
`);

  // ── 1. node check + npm install ───────────────────────────────────────────
  const major = parseInt(process.versions.node.split('.')[0], 10);
  if (major < 18) die(`Node.js 18+ required (you have ${process.versions.node}).`);
  console.log(c.green('✔') + ` Node ${process.versions.node}`);

  if (!existsSync('node_modules')) {
    console.log(c.dim('Installing dependencies…'));
    const inst = run('npm', ['install', '--no-fund', '--no-audit']);
    if (!inst.ok) die('npm install failed — check your internet connection.');
  }
  console.log(c.green('✔') + ' Dependencies ready');

  // ── 2. channels ───────────────────────────────────────────────────────────
  line();
  const chansRaw = await askQ(
    'Telegram channels to mirror (comma-separated, without @)',
    'warroom, fighter_radar, news_hut'
  );
  const channels = chansRaw.split(',').map(s => s.trim().replace(/^@/, '')).filter(Boolean);
  if (channels.length === 0) die('At least one channel is required.');

  // display names: capitalize handle
  const pretty = h => h.split(/[_\s-]+/).map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
  const CHANNELS = channels.map(h => ({ handle: h, name: pretty(h) }));

  writeFileSync('src/channels.js',
    `// Generated by wizard.js — edit freely or re-run the wizard.\n` +
    `export const CHANNELS = ${JSON.stringify(CHANNELS, null, 2)};\n`);
  console.log(c.green('✔') + ` Channels: ${CHANNELS.map(x => '@' + x.handle).join(', ')}`);

  // ── 3. discord webhook ────────────────────────────────────────────────────
  line();
  console.log(c.dim('Create one in Discord: channel ⚙ Edit → Integrations → Webhooks → New → Copy URL\n'));
  let webhook = '';
  while (true) {
    webhook = await askQ('Discord webhook URL');
    if (!/^https:\/\/(discord|discordapp)\.com\/api\/webhooks\/\d+\/[\w-]+$/.test(webhook)) {
      console.log(c.red('✖ That does not look like a webhook URL. Try again.'));
      continue;
    }
    console.log(c.dim('Sending a test message to your channel…'));
    try {
      const res = await fetch(webhook, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          username: 'Telegram Relay',
          content: `🎉 **Installation complete** — this channel will now receive posts from: ${CHANNELS.map(x => '`@' + x.handle + '`').join(', ')}`
        })
      });
      if (res.ok || res.status === 204) { console.log(c.green('✔') + ' Webhook works — check your Discord channel!'); break; }
      console.log(c.red(`✖ Discord rejected it (HTTP ${res.status}). Try again.`));
    } catch (e) {
      console.log(c.red('✖ Could not reach Discord locally: ' + e.message));
      const skip = await askQ('Some networks block Discord (VPNs/sanctions). Skip validation and continue anyway? [Y/n]', 'Y');
      if (/^y/i.test(skip)) { console.log(c.green('✔') + ' Skipped — the Worker will still deliver from the cloud.'); break; }
    }
  }

  // ── 4. cloudflare login ───────────────────────────────────────────────────
  line();
  console.log(c.dim('Checking Cloudflare login…'));
  let who = run('npx', ['wrangler', 'whoami']);
  if (!who.ok || /not authenticated/i.test(who.out)) {
    console.log(c.dim('A browser window will open — log in to Cloudflare and authorize Wrangler.\n'));
    const login = spawnSync('npx', ['wrangler', 'login'], { stdio: 'inherit', shell: true });
    if (login.status !== 0) die('Cloudflare login failed.');
    who = run('npx', ['wrangler', 'whoami']);
  }
  console.log(c.green('✔') + ' Logged in to Cloudflare');

  // ── 5. KV namespace + wrangler.toml + deploy ──────────────────────────────
  line();
  const workerName = await askQ('Worker name', 'telegram-to-discord');
  const kvTitle = `${workerName}-STATE_KV`;
  console.log(c.dim(`Creating KV namespace "${kvTitle}"…`));
  let kv = run('npx', ['wrangler', 'kv', 'namespace', 'create', 'STATE_KV']);
  let kvOut = kv.out;
  if (!kv.ok || /10014|already exists/i.test(kvOut)) {
    const list = run('npx', ['wrangler', 'kv', 'namespace', 'list']);
    const m = list.out.match(new RegExp(`"id"\\s*:\\s*"([a-f0-9]{32})"[^}]*"title"\\s*:\\s*"[^"]*${kvTitle}"`)) ||
              list.out.match(new RegExp(`"title"\\s*:\\s*"[^"]*${kvTitle}"[^}]*"id"\\s*:\\s*"([a-f0-9]{32})"`));
    if (!m) die('Could not find or create the KV namespace.');
    kvOut = `existing id ${m[1]}`;
  }
  const kvId = (kvOut.match(/([a-f0-9]{32})/) || [])[1];
  if (!kvId) die('Could not parse the KV namespace id.');
  console.log(c.green('✔') + ` KV namespace ready (${kvId.slice(0, 8)}…)`);

  writeFileSync('wrangler.toml',
`name = "${workerName}"
main = "src/index.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["* * * * *"]

[[kv_namespaces]]
binding = "STATE_KV"
id = "${kvId}"
`);
  console.log(c.green('✔') + ' wrangler.toml written');

  console.log(c.dim('Deploying to Cloudflare (this creates the Worker + cron)…'));
  const dep = run('npx', ['wrangler', 'deploy']);
  const url = (dep.out.match(/https:\/\/[a-z0-9-]+\.workers\.dev/) || [])[0];
  if (!dep.ok || !url) { console.log(dep.out); die('Deploy failed — see output above.'); }
  console.log(c.green('✔') + ' Deployed: ' + c.b(url));

  // ── 6. secret + live test ─────────────────────────────────────────────────
  line();
  console.log(c.dim('Storing webhook as an encrypted Worker secret…'));
  const sec = spawnSync('npx', ['wrangler', 'secret', 'put', 'DISCORD_WEBHOOK_URL'],
    { input: webhook + '\n', encoding: 'utf8', shell: true });
  if (sec.status !== 0) { console.log((sec.stdout || '') + (sec.stderr || '')); die('Could not store the secret.'); }
  console.log(c.green('✔') + ' Secret stored');

  console.log(c.dim('Running first live sync (newest post of each channel)…'));
  await new Promise(r => setTimeout(r, 8000)); // edge propagation
  let summary = '';
  try {
    const res = await fetch(url + '/test');
    summary = await res.text();
  } catch (e) { summary = String(e.message); }

  line();
  console.log(c.green.b('  ✅  All done!\n'));
  console.log(`  Worker:  ${c.b(url)}`);
  console.log(`  Sync:    ${c.dim('automatic, every minute')}`);
  console.log(`  Test:    ${c.dim('open ' + url + '/test anytime to force a sync')}`);
  console.log(c.dim('\n  ' + summary.split('\n').slice(0, 12).join('\n  ')));
  rl.close();
}

main().catch(e => die(e.message));
