// Generated by wizard.js — edit freely or re-run the wizard.
export const CHANNELS = [
  {
    "handle": "warroom",
    "name": "Warroom"
  },
  {
    "handle": "fighter_radar",
    "name": "Fighter Radar"
  },
  {
    "handle": "news_hut",
    "name": "News Hut"
  }
];
