// Generated by wizard.js — edit freely or re-run `node wizard.js`.
export const CHANNELS = [
  { handle: 'warroom', name: 'WARROOM News' },
  { handle: 'fighter_radar', name: 'Fighter Radar' },
  { handle: 'news_hut', name: 'News Hut' }
];
